[package]
name = "dxf2json"
version = "0.1.0"
authors = ["Brett V. Forsgren <brett.forsgren@outlook.com>"]
edition = "2021"

[dependencies]
dxf = { path = "../", features = ["serialize"] }
serde = "1.*.*"
serde_json = "1.*.*"
