name: CI

on: [push, pull_request]

jobs:

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust_version: [stable, beta, nightly]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust_version }}
    - name: Report versions
      run: |
        rustc -Vv
        cargo -V
    - uses: actions/checkout@v4
    - run: cargo build --verbose
    - run: cargo test --verbose
    - run: cargo build --verbose --manifest-path ./dxf2json/Cargo.toml
    - run: cargo build --verbose --manifest-path ./examples/Cargo.toml

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        components: rustfmt
    - uses: actions/checkout@v4
    - run: cargo fmt --all -- --check

  publish:
    name: Publish to crates.io
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build, formatting]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo publish --token ${{ secrets.CRATES_IO_API_KEY }} --verbose
